name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Git branch name
        id: git-branch-name
        uses: EthanSK/git-branch-name-action@v1
      - name: Checkout the source code
        uses: actions/checkout@v3
      - name: Install & display rust toolchain
        run: |
          rustup show
          rustup component add rust-src
      - name: Cache build
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            /usr/share/rust/.rustup/
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-
      - name: Check targets are installed correctly
        run: rustup target list --installed
      - name: Cache Crates
        uses: actions/cache@v3
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-rust-${{ hashFiles('rust-toolchain.toml') }}
          restore-keys: |
            ${{ runner.os }}-rust
      - name: Restore cached Primes
        id: cache-primes-restore
        uses: actions/cache/restore@v3
        with:
          path: |
            **/target
          key: artifacts-${{ runner.os }}-${{ env.GIT_BRANCH_NAME }}
          restore-keys: |
            artifacts-${{ runner.os }}-
      - name: Check if cargo-contract exists
        id: check-cargo-contract
        continue-on-error: true
        run: cargo contract --version
      - name: Install cargo contract
        if: ${{ steps.check-cargo-contract.outcome == 'failure' }}
        run: |
          sudo apt-get install binaryen
          cargo install cargo-dylint dylint-link
          cargo install --force --locked cargo-contract
      - name: Compile checks
        env:
          CARGO_INCREMENTAL: 1
        run: |
          manifest_paths=`find contracts -type f -name Cargo.toml`
          echo $manifest_paths
          for manifest_path in $manifest_paths; do
            echo $manifest_path
            cargo contract check --manifest-path $manifest_path
          done
      - name: Save Primes
        id: cache-primes-save
        uses: actions/cache/save@v3
        with:
          path: |
            **/target
          key: artifacts-${{ runner.os }}-${{ env.GIT_BRANCH_NAME }}
      - name: test
        run: cargo test
        env:
          CARGO_INCREMENTAL: 1
